### ISSUE TITLE
What is ec2-23-21-64-152.compute-1.amazonaws.com and why should we trust it?

### ISSUE THREAD

**Issue by aalbertson** [yaronn/wopr#4]
What is this node, and why should we send our reports and traffic there?

**Comment by yaronn** [comment]
It's a reference implementation for a service that sends wopr reports for consumption with curl.
Do not send any secret data to it - that's there just to show capabilities. It's a box I manage in amazon.
If you want you can setup your own viewer renderer and secure it for your needs.
I will make that clear, thanks for raising this.
