### ISSUE TITLE
Server crashes with `screen.program.destroy is not a function` after displaying first dashboard

### ISSUE THREAD

**Issue by soulshake** [yaronn/wopr#9]
### What I do
- I'm installing dependencies by running the following command (in `wopr/`):

```
# Note: I'm installing specific versions here because I was also having trouble 
# running simply `npm install`.
$ npm install \
    blessed@0.1.7 \
    blessed-contrib@2.3.1 \
    xml2js@0.4.9
```
- I launch the wopr server (with `node server.js`) and it awaits connections as expected.
- From the client, I run `curl -N localhost:1337/\[0-2\]\?auto\&cols=$((COLUMNS))`.
### What I expect

The server should display all 3 dashboards in the terminal of the client.
### What I see instead
- The server displays the first dashboard as expected, then crashes a few seconds later, citing the error `screen.program.destroy is not a function`.
#### Client-side output:

```
[1/3]: localhost:1337/0?auto&cols=117 --> <stdout>
--_curl_--localhost:1337/0?auto&cols=117
curl: (18) transfer closed with outstanding read data remaining

[3/3]: localhost:1337/2?auto&cols=117 --> <stdout>
--_curl_--localhost:1337/2?auto&cols=117
curl: (7) Failed to connect to localhost port 1337: Connection refused
```
#### The server-side logs:

```
Server running at http://127.0.0.1:1337/
TypeError: screen.program.destroy is not a function
    at clean (/src/wopr/server/presenter.js:72:18)
    at null._onTimeout (/src/wopr/server/presenter.js:57:9)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:426:15)
    at OutputBuffer.write (/src/wopr/node_modules/blessed-contrib/lib/server-utils.js:12:19)
    at Program.flush (/src/wopr/node_modules/blessed/lib/program.js:1473:15)
    at Screen.leave (/src/wopr/node_modules/blessed/lib/widgets/screen.js:273:16)
    at process.<anonymous> (/src/wopr/node_modules/blessed/lib/widgets/screen.js:184:10)
    at emitOne (events.js:90:13)
    at process.emit (events.js:182:7)
    at process._fatalException (node.js:264:26)
error: Forever detected script exited with code: 1
```
### To reproduce the issue

I'm installing wopr in a Docker container. There are Dockerfiles for the [server](https://github.com/soulshake/wopr/blob/master/Dockerfile) and even the [client](https://github.com/soulshake/wopr/blob/master/client/Dockerfile) in my fork of this repo.

**Comment by yaronn** [comment]
Thanks for opening both issues. I was able to reproduce this error.
Initially I thought it is related to node version but not too sure any
more. I will check this further. Until then I recommend to either user the
public version (tty.zone) if information is not confidential, or use the
local client viewer (wopr binary) or use a local server with single page
documents.

On Mon, Mar 28, 2016 at 8:12 PM, AJ Bowen notifications@github.com wrote:

> What I do
> - I'm installing dependencies by running the following command (in
>   wopr/):
> 
> # Note: I'm installing specific versions here because I was also having trouble
> 
> # running simply `npm install`.
> 
> $ npm install \
>     blessed@0.1.7 \
>     blessed-contrib@2.3.1 \
>     xml2js@0.4.9
> - I launch the wopr server (with node server.js) and it awaits
>   connections as expected.
> - From the client, I run curl -N
>   localhost:1337/[0-2]\?auto&cols=$((COLUMNS)).
> 
> What I expect
> 
> The server should display all 3 dashboards in the terminal of the client.
> What I see instead
> - The server displays the first dashboard as expected, then crashes a
>   few seconds later, citing the error screen.program.destroy is not a
>   function.
> 
> Client-side output:
> 
> [1/3]: localhost:1337/0?auto&cols=117 --> <stdout>
> --_curl_--localhost:1337/0?auto&cols=117
> curl: (18) transfer closed with outstanding read data remaining
> 
> [3/3]: localhost:1337/2?auto&cols=117 --> <stdout>
> --_curl_--localhost:1337/2?auto&cols=117
> curl: (7) Failed to connect to localhost port 1337: Connection refused
> 
> The server-side logs:
> 
> Server running at http://127.0.0.1:1337/
> TypeError: screen.program.destroy is not a function
>     at clean (/src/wopr/server/presenter.js:72:18)
>     at null._onTimeout (/src/wopr/server/presenter.js:57:9)
>     at tryOnTimeout (timers.js:224:11)
>     at Timer.listOnTimeout (timers.js:198:5)
> Error: write after end
>     at ServerResponse.OutgoingMessage.write (_http_outgoing.js:426:15)
>     at OutputBuffer.write (/src/wopr/node_modules/blessed-contrib/lib/server-utils.js:12:19)
>     at Program.flush (/src/wopr/node_modules/blessed/lib/program.js:1473:15)
>     at Screen.leave (/src/wopr/node_modules/blessed/lib/widgets/screen.js:273:16)
>     at process.<anonymous> (/src/wopr/node_modules/blessed/lib/widgets/screen.js:184:10)
>     at emitOne (events.js:90:13)
>     at process.emit (events.js:182:7)
>     at process._fatalException (node.js:264:26)
> error: Forever detected script exited with code: 1
> 
> To reproduce the issue
> 
> I'm installing wopr in a Docker container. There are Dockerfiles for the
> server https://github.com/soulshake/wopr/blob/master/Dockerfile and
> even the client
> https://github.com/soulshake/wopr/blob/master/client/Dockerfile in my
> fork of this repo.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/yaronn/wopr/issues/9

## 

I'm on Twitter (@YaronNaveh http://twitter.com/#!/YaronNaveh)

**Comment by yaronn** [comment]
Hi @soulshake, I believe I have fixed this issue, can you try again?

**Comment by yaronn** [comment]
I've been using explicitly blessed-contrib@2.3.1. blessed@0.1.11 - checking now if this is a must but please use these versions too

**Comment by yaronn** [comment]
ok, I updated package.json to reflect the right versions so you can try now from master

**Comment by soulshake** [comment]
Works now, thanks!
